const KEY='kanakPracticeV3';
const SUBJECTS={
 maths:{name:'Maths',icon:'🔢',desc:'Numbers, shapes & problem solving',topics:[['addition','Addition','Add 2–3 digit numbers'],['subtraction','Subtraction','Subtract with confidence'],['multiplication','Multiplication','Tables & multiplication'],['division','Division','Simple division'],['fractions','Fractions','Parts of a whole'],['time','Time','Read clocks & solve time problems']]},
 english:{name:'English',icon:'📘',desc:'Grammar, vocabulary & comprehension',topics:[['nouns','Nouns','People, places, animals & things'],['pronouns','Pronouns','I, you, he, she, they & more'],['verbs','Verbs','Action and being words'],['adjectives','Adjectives','Words that describe'],['tenses','Tenses','Past, present & future'],['comprehension','Comprehension','Read and understand']]},
 hindi:{name:'Hindi',icon:'🇮🇳',desc:'हिंदी व्याकरण और शब्द',topics:[['sangya','संज्ञा','नाम बताने वाले शब्द'],['sarvanam','सर्वनाम','संज्ञा के स्थान पर शब्द'],['kriya','क्रिया','काम बताने वाले शब्द'],['ling','लिंग','पुल्लिंग और स्त्रीलिंग'],['vachan','वचन','एकवचन और बहुवचन'],['vilom','विलोम शब्द','उल्टे अर्थ वाले शब्द']]},
 evs:{name:'EVS',icon:'🌱',desc:'Our world, science & everyday life',topics:[['family','My Family','Families and relationships'],['caring','Sharing and Caring','Helping and kindness'],['games','Games Are Fun!','Play, exercise & teamwork'],['work','Work People Do','Jobs and community helpers'],['plants','World of Plants','Plants around us'],['animals','World of Animals','Animals and their needs']]}
};
const BANK={
 'maths:addition':[
  ['What is 245 + 123?',['358','368','378','388'],1],['What is 300 + 45?',['345','355','335','305'],0],['What is 468 + 257?',['715','725','735','745'],1],['A shop has 235 pencils and gets 148 more. How many?',['373','383','393','403'],1],['What must be added to 378 to make 500?',['112','122','132','142'],1]
 ],
 'maths:subtraction':[['95 − 42 = ?',['43','53','63','73'],1],['700 − 200 = ?',['400','500','600','700'],1],['634 − 278 = ?',['346','356','366','376'],1],['850 books − 275 borrowed = ?',['565','575','585','595'],1],['What is 600 − 125?',['465','475','485','495'],1]],
 'maths:multiplication':[['6 × 4 = ?',['20','24','28','30'],1],['8 × 5 = ?',['35','40','45','50'],1],['12 × 7 = ?',['74','84','94','104'],1],['9 bags have 6 marbles each. How many?',['45','48','54','60'],2],['Which is the same as 7 × 8?',['7+8','8+8+8+8+8+8+8','7+7+8','8×7+1'],1]],
 'maths:division':[['20 ÷ 5 = ?',['2','4','5','10'],1],['12 sweets shared among 3 children. Each gets?',['3','4','5','6'],1],['48 ÷ 6 = ?',['6','7','8','9'],2],['36 pencils in groups of 4. How many groups?',['7','8','9','10'],2],['A number divided by 5 gives 9. What is it?',['35','40','45','50'],2]],
 'maths:fractions':[['Which fraction means one half?',['1/2','1/3','2/3','2/4'],0],['One of 4 equal pizza pieces is what fraction?',['1/2','1/3','1/4','4/1'],2],['Which is greater?',['1/4','3/4','1/8','2/8'],1],['3 of 8 equal parts are shaded. Fraction?',['3/5','5/8','3/8','8/3'],2],['Which fraction is equal to 1/2?',['1/3','2/4','3/8','2/6'],1]],
 'maths:time':[['How many minutes are in one hour?',['30','45','60','100'],2],['At 3:00, where is the minute hand?',['3','6','9','12'],3],['8:00 to 2:00 is how long?',['4 hours','5 hours','6 hours','7 hours'],2],['30 minutes after 4:15 is?',['4:30','4:45','5:00','5:15'],1],['5:40 plus 1 hour 20 minutes is?',['6:40','6:50','7:00','7:10'],2]],
 'english:nouns':[['Which word is a noun?',['run','beautiful','school','quickly'],2],['Which is an animal name?',['tiger','jump','green','slowly'],0],['Which sentence has two nouns?',['Birds fly.','Riya reads a book.','Run quickly.','Very happy.'],1],['Which word names a place?',['Delhi','happy','swim','soft'],0],['Which group contains only nouns?',['cat, school, teacher','run, jump, sing','blue, tall, kind','slowly, loudly, softly'],0]],
 'english:pronouns':[['Choose: ___ am ready.',['He','I','They','She'],1],['Ravi is my friend. ___ is kind.',['He','She','It','They'],0],['Meena and I are sisters. ___ play together.',['He','She','We','It'],2],['The dogs are hungry. ___ need food.',['It','He','They','She'],2],['My brother and I went home.',['They went home.','We went home.','He went home.','It went home.'],1]],
 'english:verbs':[['Which word is a verb?',['jump','yellow','chair','happy'],0],['Birds ___ in the sky.',['fly','blue','soft','quick'],0],['Which sentence has an action word?',['The ball is red.','The boy runs.','The sky is blue.','The flower is pretty.'],1],['She ___ milk every morning.',['drink','drinks','drinking','drank'],1],['Yesterday, we ___ to the park.',['go','goes','went','going'],2]],
 'english:adjectives':[['Which word describes "red apple"?',['apple','red','a','the'],1],['The tall boy smiled. Which is the adjective?',['boy','smiled','tall','the'],2],['Which sentence has an adjective?',['The dog runs.','The small dog runs.','Run fast.','Dogs bark.'],1],['Which word describes a lemon?',['sour','jump','eat','quickly'],0],['Which sentence has two adjectives?',['The small red ball rolled.','The ball rolled quickly.','The boy ran.','She sings.'],0]],
 'english:tenses':[['I ___ to school yesterday.',['go','goes','went','going'],2],['She ___ every day.',['plays','played','will play','playing'],0],['Tomorrow, we ___ grandma.',['visited','visit','will visit','visiting'],2],['Which is past tense?',['I eat lunch.','I ate lunch.','I will eat lunch.','I am eating lunch.'],1],['Which correctly shows future?',['They played tomorrow.','They play yesterday.','They will play tomorrow.','They playing tomorrow.'],2]],
 'english:comprehension':[['Mia has a blue kite. What colour is it?',['Red','Green','Blue','Yellow'],2],['Mia flies the kite where?',['At school','In the park','At home','In a shop'],1],['Arun packed an umbrella because dark clouds filled the sky. Why?',['It was sunny','He was swimming','It might rain','He lost his bag'],2],['What was in the sky?',['Stars','Dark clouds','Balloons','Only birds'],1],['Nina watered plants every morning and new leaves appeared. What can we infer?',['Plants need care to grow','Plants never need water','Nina cut them','Leaves appear only at night'],0]],
 'hindi:sangya':[['इनमें से संज्ञा शब्द कौन-सा है?',['दौड़ना','किताब','सुंदर','धीरे'],1],['दिल्ली किसका नाम है?',['व्यक्ति','स्थान','वस्तु','क्रिया'],1],['रीमा आम खाती है। संज्ञा कौन-से हैं?',['रीमा और आम','खाती','है','और'],0],['वस्तु का नाम कौन-सा है?',['कुर्सी','दौड़ना','मीठा','जल्दी'],0],['केवल संज्ञा शब्दों का समूह चुनिए।',['घर, बच्चा, पेड़','दौड़ना, खेलना, गाना','सुंदर, बड़ा, मीठा','धीरे, जल्दी, बाहर'],0]],
 'hindi:sarvanam':[['मैं किस प्रकार का शब्द है?',['संज्ञा','सर्वनाम','क्रिया','विशेषण'],1],['मोहन बाजार गया। ___ फल लाया।',['वह','वे','मैं','हम'],0],['सीमा और रीना पढ़ रही हैं। ___ मेहनती हैं।',['वह','वे','मैं','यह'],1],['हम का प्रयोग किसके लिए होता है?',['एक व्यक्ति','एक वस्तु','एक से अधिक बोलने वाले','स्थान'],2],['रवि और मैं स्कूल गए। सही सर्वनाम?',['वे स्कूल गए।','हम स्कूल गए।','वह स्कूल गया।','मैं स्कूल गया।'],1]],
 'hindi:kriya':[['क्रिया शब्द पहचानिए।',['सुंदर','खेलना','लाल','घर'],1],['बच्चे दौड़ते हैं। क्रिया?',['बच्चे','दौड़ते','हैं','में'],1],['माँ खाना बनाती है। क्रिया?',['माँ','खाना','बनाती','है'],2],['काम बताने वाला शब्द कौन-सा है?',['कूदना','नीला','किताब','बड़ा'],0],['कल हम पार्क जाएंगे। क्रिया?',['कल','हम','पार्क','जाएंगे'],3]],
 'hindi:ling':[['लड़का का स्त्रीलिंग?',['लड़की','लड़के','लड़कियाँ','लड़कों'],0],['रानी का पुल्लिंग?',['राजा','रानी','राजी','रान'],0],['मोर का स्त्रीलिंग?',['मोरनी','मोरिया','मोरी','मोरिन'],0],['अध्यापक का स्त्रीलिंग?',['अध्यापिका','अध्यापकी','अध्यापकनी','अध्यापिका'],0],['सही जोड़ी चुनिए।',['भाई—बहन','राजा—राजा','लड़का—लड़के','मोर—मोर'],0]],
 'hindi:vachan':[['लड़का का बहुवचन?',['लड़की','लड़के','लड़कापन','लड़कों'],1],['किताबें किस वचन में है?',['एकवचन','बहुवचन','दोनों','कोई नहीं'],1],['बच्चे खेल रहे हैं। बच्चे है:',['एकवचन','बहुवचन','स्त्रीलिंग','क्रिया'],1],['फूल का बहुवचन?',['फूले','फूलों','फूल','फूलें'],2],['किस वाक्य में बहुवचन है?',['लड़का दौड़ता है।','बच्चे खेलते हैं।','रीमा पढ़ती है।','कुत्ता भौंकता है।'],1]],
 'hindi:vilom':[['दिन का विलोम?',['सुबह','रात','दोपहर','शाम'],1],['बड़ा का विलोम?',['ऊँचा','छोटा','लंबा','मोटा'],1],['अच्छा का विलोम?',['सुंदर','बुरा','मीठा','साफ'],1],['ऊपर का विलोम?',['आगे','नीचे','पीछे','पास'],1],['सही विलोम जोड़ी चुनिए।',['नया—पुराना','मीठा—सुंदर','तेज—लंबा','साफ—बड़ा'],0]],
 'evs:family':[['A family is a group of people who are usually ___.',['related','unrelated','strangers','neighbours only'],0],['Two children born at the same time to the same mother are called:', ['cousins','twins','neighbours','friends'],1],['Parents and their children living together are commonly called a:', ['nuclear family','park family','school family','market family'],0],['Our father’s parents are our:', ['maternal grandparents','paternal grandparents','cousins','siblings'],1],['Which is true?',['All families are exactly the same.','Families can be small or large.','Only children make a family.','Friends are always family members.'],1]],
 'evs:caring':[['Sharing with others shows:', ['kindness','anger','laziness','fear'],0],['We should help family members when they need:', ['help','trouble','nothing','noise'],0],['Which action shows caring?',['Ignoring an injured friend','Helping an elderly person','Wasting food','Breaking toys'],1],['Why should we share fairly?',['To be kind and helpful','To make others sad','To waste things','To avoid friends'],0],['Two friends want the same toy. Best choice?',['fight','take it away','take turns','hide it'],2]],
 'evs:games':[['Playing games can help keep our body:', ['healthy','sleepy all day','dirty','weak'],0],['Which is a team game?',['football','sleeping','reading alone','brushing'],0],['Why are rules important in games?',['They make games fair and safe.','They stop everyone playing.','They make games longer only.','They are not needed.'],0],['Good players should respect:', ['only themselves','other players and rules','nobody','only the winner'],1],['If your team loses, you should:', ['blame everyone','congratulate the other team and learn','break equipment','stop being kind'],1]],
 'evs:work':[['A person who teaches students is a:', ['teacher','farmer','pilot','carpenter'],0],['A person who grows crops is a:', ['farmer','doctor','driver','tailor'],0],['Who helps sick people in a hospital?',['doctor','carpenter','postman','chef'],0],['A person who stitches clothes is a:', ['tailor','pilot','gardener','teacher'],0],['Why are different workers important?',['They help society in different ways.','Only one job matters.','Jobs are not useful.','Everyone does the same job.'],0]],
 'evs:plants':[['Which plant part usually grows below soil?',['root','flower','leaf','fruit'],0],['Leaves help a plant to:', ['make food','walk','hear','sleep'],0],['Which part carries water from roots?',['stem','flower','fruit','seed'],0],['Which is a plant product we can eat?',['mango','stone','plastic','glass'],0],['If a plant gets no water for a long time, it may:', ['wilt','grow faster','walk','do nothing'],0]],
 'evs:animals':[['Which animal is a mammal?',['cow','sparrow','fish','butterfly'],0],['Which animal can fly?',['elephant','sparrow','cow','dog'],1],['Animals need food, water and a safe place to:', ['live','read','write','cook'],0],['Which animal lives mainly in water?',['fish','lion','camel','horse'],0],['Why do animals have different body features?',['They help animals survive.','Only for decoration.','All animals need the same features.','They do not help.'],0]]
};
const state={screen:'home',subject:null,topic:null,level:null,paper:[],index:0,selected:null,locked:false,score:0,seconds:0,timer:null,started:0};
function stats(){try{return JSON.parse(localStorage.getItem(KEY))||{papers:[],topics:{}}}catch(e){return{papers:[],topics:{}}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function time(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function render(){clearInterval(state.timer);state.timer=null;document.getElementById('homeBtn').classList.toggle('hidden',state.screen==='home');const a=document.getElementById('app');if(state.screen==='home')a.innerHTML=home();if(state.screen==='subject')a.innerHTML=subject();if(state.screen==='paper'){a.innerHTML=paper();startTimer()}if(state.screen==='result')a.innerHTML=result();if(state.screen==='dashboard')a.innerHTML=dashboard()}
function home(){let s=stats();return `<section class="hero"><div class="emoji">🎒✨</div><h1>Ready to Learn?</h1><p>Pick a subject and start your Class 3 practice.</p></section><section class="grid">${Object.entries(SUBJECTS).map(([id,x])=>`<button class="card subject" data-subject="${id}"><div class="icon">${x.icon}</div><h2>${esc(x.name)}</h2><p>${esc(x.desc)}</p></button>`).join('')}</section><button class="primary dashbtn" id="dash">📊 Parent Progress Dashboard</button><div class="strip"><span><b>${s.papers.length}</b> practice papers completed</span><span>📝 20 questions · 🎯 3 difficulty levels · ⏱️ timed papers</span></div>`}
function subject(){let x=SUBJECTS[state.subject];return `<section class="page"><div class="head"><div><h1>${x.icon} ${esc(x.name)} Practice</h1><p>Choose a topic, then Easy, Medium or Hard. Every paper has 20 questions.</p></div></div><div class="topicgrid">${x.topics.map(t=>`<div class="card topic"><h3>${esc(t[1])}</h3><p>${esc(t[2])}</p><div class="levels"><button class="level" data-topic="${t[0]}" data-level="easy">🟢 Easy</button><button class="level" data-topic="${t[0]}" data-level="medium">🟡 Medium</button><button class="level" data-topic="${t[0]}" data-level="hard">🔴 Hard</button></div></div>`).join('')}</div><div class="actions"><button class="secondary" id="back">← Back</button><button class="secondary" id="dash2">📊 Progress</button></div></section>`}
function makePaper(){let bank=BANK[state.subject+':'+state.topic]||[];let qs=[];while(qs.length<20)qs.push(...shuffle(bank));state.paper=qs.slice(0,20);state.index=0;state.selected=null;state.locked=false;state.score=0;state.started=Date.now();state.seconds=state.level==='easy'?900:state.level==='medium'?780:660;state.screen='paper'}
function startTimer(){state.timer=setInterval(()=>{state.seconds--;let e=document.getElementById('timer');if(e)e.textContent=time(Math.max(0,state.seconds));if(state.seconds<=0)finish(true)},1000)}
function paper(){let q=state.paper[state.index],topic=SUBJECTS[state.subject].topics.find(t=>t[0]===state.topic)?.[1]||state.topic;return `<section class="card paper"><div class="paperhead"><div><span class="badge">${SUBJECTS[state.subject].icon} ${esc(SUBJECTS[state.subject].name)} • ${esc(topic)} • ${state.level==='easy'?'🟢 Easy':state.level==='medium'?'🟡 Medium':'🔴 Hard'}</span><h1>Practice Paper</h1></div><div><div class="timer" id="timer">${time(state.seconds)}</div><strong>${state.index+1}/20</strong></div></div><div class="progress"><div style="width:${state.index/20*100}%"></div></div><div class="q"><h2>Practice question: ${esc(q[0])}</h2><div class="options">${q[1].map((o,i)=>`<button class="option ${state.selected===i?'selected':''}" data-answer="${i}">${esc(o)}</button>`).join('')}</div>${state.locked?`<div class="feedback">${state.selected===q[2]?'✅ Correct! Great job!':'💡 Not quite. Correct answer: <b>'+esc(q[1][q[2]])+'</b>.'}</div>`:''}</div><div class="actions"><button class="secondary" id="exit">Exit Paper</button><button class="primary" id="next">${state.index===19?'Finish 🎉':'Next →'}</button></div></section>`}
function finish(timeUp=false){clearInterval(state.timer);state.timer=null;let s=stats(),k=state.subject+':'+state.topic;s.topics[k]=s.topics[k]||{a:0,c:0};s.topics[k].a+=20;s.topics[k].c+=state.score;s.papers.push({date:new Date().toISOString(),subject:state.subject,topic:state.topic,level:state.level,score:state.score,total:20,time:Math.round((Date.now()-state.started)/1000),timeUp});s.papers=s.papers.slice(-100);save(s);state.screen='result';render()}
function result(){let p=Math.round(state.score/20*100);return `<section class="page result"><div class="big">${p>=90?'🏆':p>=75?'🌟':p>=50?'💪':'🌱'}</div><h1>${p>=90?'Fantastic work!':p>=75?'Great job!':'Keep practising!'}</h1><p>You completed your practice paper.</p><div class="resultgrid"><div class="card stat"><div class="num">${state.score}/20</div><small>Score</small></div><div class="card stat"><div class="num">${p}%</div><small>Accuracy</small></div><div class="card stat"><div class="num">${time(Math.round((Date.now()-state.started)/1000))}</div><small>Time</small></div></div><div class="actions"><button class="secondary" id="again">↻ Try Again</button><button class="primary" id="dash3">📊 View Progress</button></div></section>`}
function dashboard(){let s=stats(),total=s.papers.reduce((a,p)=>a+p.total,0),correct=s.papers.reduce((a,p)=>a+p.score,0);return `<section class="page"><div class="head"><div><h1>📊 Kanak's Progress</h1><p>Saved on this browser using local storage. No account is required.</p></div></div><div class="resultgrid"><div class="card stat"><div class="num">${s.papers.length}</div><small>Papers completed</small></div><div class="card stat"><div class="num">${correct}</div><small>Correct answers</small></div><div class="card stat"><div class="num">${total?Math.round(correct/total*100):0}%</div><small>Overall accuracy</small></div></div><div class="card dashcard"><h2>Subject performance</h2>${Object.entries(SUBJECTS).map(([id,x])=>{let rows=s.papers.filter(p=>p.subject===id),a=rows.reduce((n,p)=>n+p.total,0),c=rows.reduce((n,p)=>n+p.score,0),p=a?Math.round(c/a*100):0;return `<div class="barrow"><b>${x.icon} ${x.name}</b><div class="bar"><span style="width:${p}%"></span></div><strong>${p}%</strong></div>`}).join('')}</div><div class="card dashcard"><h2>Recent papers</h2>${s.papers.length?[...s.papers].reverse().slice(0,8).map(p=>`<div class="barrow"><span>${SUBJECTS[p.subject].name}</span><div>${esc(p.topic)} · ${esc(p.level)}</div><strong>${p.score}/20</strong></div>`).join(''):'<div class="empty">No papers yet. Start practising to build the dashboard.</div>'}</div><div class="actions"><button class="secondary" id="backhome">← Home</button>${s.papers.length?'<button class="secondary" id="reset">Reset Progress</button>':''}</div></section>`}
document.addEventListener('click',e=>{let b=e.target.closest('[data-subject]');if(b){state.subject=b.dataset.subject;state.screen='subject';render();return}b=e.target.closest('[data-topic][data-level]');if(b){state.topic=b.dataset.topic;state.level=b.dataset.level;makePaper();render();return}if(e.target.closest('#homeBtn,#back,#backhome')){state.screen='home';render();return}if(e.target.closest('#dash,#dash2,#dash3')){state.screen='dashboard';render();return}b=e.target.closest('[data-answer]');if(b&&!state.locked){state.selected=+b.dataset.answer;render();return}if(e.target.closest('#next')){if(state.selected===null){alert('Please choose an answer 😊');return}if(!state.locked){state.locked=true;if(state.selected===state.paper[state.index][2])state.score++;render()}else if(state.index===19)finish(false);else{state.index++;state.selected=null;state.locked=false;render()}return}if(e.target.closest('#exit')){if(confirm('Exit this paper? Your current paper will not be saved.')){state.screen='subject';render()}return}if(e.target.closest('#again')){makePaper();render();return}if(e.target.closest('#reset')){if(confirm('Reset all saved progress on this browser?')){localStorage.removeItem(KEY);render()}}});render();
